sudo: required
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo pip install ansible==2.0.2.0
  - sudo pip install docker-py
  - sudo pip install six --upgrade
  - sudo apt-get install -y sshpass

services:
  - docker
# command to run tests
script:
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles
  - cd tests/files
#  - wget http://files.justinholmes.co/jboss-eap-6.4.0.zip
#  - wget http://files.justinholmes.co/jboss-eap-6.4.7-patch.zip
  - cd ..
  - ansible-playbook test1.yml -i inventory
